name: 'Bornlogic Nuget Dependabot'
description: 'A Github action deal with updates in csproj nuget package dependencies.'
branding:
  icon: user-plus
  color: gray-dark
inputs:
  username:
    description: 'The Nuget Username, for example: \"samples\".'
    required: false
  nuget-source:
    description: 'The Nuget Source To Override, for example: \"https://api.nuget.org/v3/octorat/index.json\".'
    required: false
  nuget-password:
    description: 'The Nuget Password, for example: \"GHP_12345678\".'
    required: false
outputs:
  summary-title:
    description: 'The title of the code metrics action.'
  summary-details:
    description: 'A detailed summary of all the projects that were flagged.'
  updated-metrics:
    description: 'A boolean value, indicating whether or not the CODE_METRICS.md was updated as a result of running this action.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-n'
    - ${{ inputs.username }}
    - '-n'
    - ${{ inputs.nuget-source }}
    - '-p'
    - ${{ inputs.password }}
